### ISSUE TITLE
Add Disqus Comment System Support

### ISSUE THREAD

**Issue by nolddor** [kaptn3/future-imperfect#10]
As a user, It would be awesome If I've been able to **comment in post pages**.

Any plan to include [Disqus](https://disqus.com/) in this theme?
By the way, congrats it's a superb theme anyway!!

**Comment by kaptn3** [comment]
@nolddor , I think, it is good idea, I will try to implement it as soon as possible! :)
Thank you!

**Comment by kaptn3** [comment]
Feature added! [commit](https://github.com/ViKapitoshka/blog/commit/d361a55a42d437c1559ca3027461a7c371dc2c54)

**Comment by kaptn3** [comment]
I will change comments tool, disqus no suitable

**Comment by kaptn3** [comment]
Now hypercomments
